[package]
name = "vmread-sys-kmod"
version = "0.1.0"
authors = ["Aurimas Blažulionis <0x60@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vmread-sys = { path="../vmread-sys", features=["kmod_rw"] }
